### ISSUE TITLE
Create Micro-package to Flatten/Format `user_agent` data for `ATM`

### ISSUE THREAD

**Issue by nelsonic** [dwyl/user_agent#1]
`while` reading the code: https://github.com/elixir-inspector/ua_inspector/blob/master/lib/ua_inspector.ex
and tests: https://github.com/elixir-inspector/ua_inspector/blob/master/test/ua_inspector/database/init_test.exs

I decided to create a _thin_ wrapper that flattens the `user_agent` data into the format that we need.

Spoiled for choice on package names:

https://hex.pm/packages/ua
<img width="956" alt="image" src="https://github.com/dwyl/atm/assets/194400/a521d3f6-8b75-4264-b790-a30c9d162d5b">

https://hex.pm/packages/user_agent
<img width="956" alt="image" src="https://github.com/dwyl/atm/assets/194400/575be7b9-8c35-4280-91cf-93add3d1a7f5">

# Todo

+ [ ] Create `ua` package following our usual template 🆕 
+ [ ] Flatten/format the data we need and return as `Map` 🧑‍💻 
+ [ ] Write _extensive_ tests using available `user_agent` data 
+ [ ] Publish `ua` package to `Hex.pm` 📦 
+ [ ] Use `ua` in `ATM` :shipit: 

P.S: Sponsoring https://github.com/mneudert for as long as we use the fine work he has done. `#first`

<img width="1337" alt="image" src="https://github.com/dwyl/user_agent/assets/194400/06282a44-1a78-4bcb-aede-5883f3d97bb6">

Just a way to say "thanks" for the `code`. 🙏

**Comment by nelsonic** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent
<img width="1185" alt="mdn-advert-react-course" src="https://github.com/dwyl/user_agent/assets/194400/3eeab3b0-9780-479e-8ba6-a7e6e64faa3d">

WTF!? 🤷‍♂️ 🤦‍♂️ 

<img width="1204" alt="frontend-masters-react" src="https://github.com/dwyl/user_agent/assets/194400/38c2b3db-3f59-4cd2-9e03-70f1a698137b">

Don't want to see ads? Pay. Monthly! https://developer.mozilla.org/en-US/plus?ref=nope#subscribe
<img width="1231" alt="image" src="https://github.com/dwyl/user_agent/assets/194400/32a5a99a-b541-4b16-9ffc-9e7e7ad848a8">

**Comment by nelsonic** [comment]
Sadly, getting the following:

```elixir
UserAgent.parse("Mozilla/5.0 (iPad; CPU OS 7_0_4 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11B554a Safari/9537.53")
%{
  browser_family: :unknown,
  client: :unknown,
  device: :unknown,
  os: :unknown,
  os_family: :unknown,
  user_agent: "Mozilla/5.0 (iPad; CPU OS 7_0_4 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11B554a Safari/9537.53"
}
```

I'd have thought this `user_agent` would be fairly straightforward to parse ... 💭

**Comment by nelsonic** [comment]
https://docs.rs/user-agent-parser/latest/user_agent_parser/  hmm ... 💭

**Comment by nelsonic** [comment]
Continue: 
+ https://github.com/elixir-inspector/ua_inspector/blob/master/lib/ua_inspector.ex
+ https://github.com/elixir-inspector/ua_inspector/blob/master/test/ua_inspector/parser/browser_engine_test.exs

**Comment by nelsonic** [comment]
https://hexdocs.pm/ua_inspector/UAInspector.html
https://hexdocs.pm/ua_inspector/UAInspector.Config.html
https://hexdocs.pm/ua_inspector/UAInspector.Supervisor.html#summary

**Comment by nelsonic** [comment]
https://github.com/ikeikeikeike/common_device_detector/blob/master/lib/common_device_detector/download/database.ex
